"""empty message

Revision ID: 27e8a1a2c948
Revises: 756a4bd69c03
Create Date: 2020-05-04 20:59:41.828756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e8a1a2c948'
down_revision = '756a4bd69c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'venue', 'state', ['state_id'], ['id'])
    op.drop_column('venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'state_id')
    # ### end Alembic commands ###
