"""empty message

Revision ID: 48a8f88605c1
Revises: 2f0f5cfc4075
Create Date: 2020-05-03 14:49:14.172719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a8f88605c1'
down_revision = '2f0f5cfc4075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
