"""empty message

Revision ID: 77b18af0c949
Revises: d6c60d37b549
Create Date: 2020-05-14 16:31:42.121163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b18af0c949'
down_revision = 'd6c60d37b549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column(
        'seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('artist', 'seeking_talent')
    # ### end Alembic commands ###
    op.execute('UPDATE artist SET seeking_venue=true WHERE id = 1')
    op.execute('UPDATE artist SET seeking_venue=false WHERE id = 2')
    op.execute('UPDATE artist SET seeking_venue=false WHERE id = 3')
    op.execute("UPDATE artist SET seeking_description='Looking for shows to perform at in the San Francisco Bay Area!\' WHERE id = 1")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_talent',
                                      sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
