"""empty message

Revision ID: 837706595e1b
Revises: 640bd675608e
Create Date: 2020-05-13 16:45:37.117709

"""
from alembic import op
import sqlalchemy as sa
from dateutil.parser import parse

# revision identifiers, used by Alembic.
revision = '837706595e1b'
down_revision = '640bd675608e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'city', 'state', ['state_id'], ['id'])
    # ### end Alembic commands ###
    op.execute('UPDATE city SET state_id=5 WHERE id = 1')
    op.execute('UPDATE city SET state_id=27 WHERE id = 2')
    op.execute(
        "ALTER TABLE show ALTER column start_time type timestamp USING start_time::timestamp without time zone")
    op.execute(
        f"INSERT INTO show (artist_id,venue_id, start_time) VALUES (1,1, '{parse('2019-05-21T21:30:00.000Z')}')")
    op.execute(
        f"INSERT INTO show (artist_id,venue_id, start_time) VALUES (2,3, '{parse('2019-06-15T23:00:00.000Z')}')")
    op.execute(
        f"INSERT INTO show (artist_id,venue_id, start_time) VALUES (3,3, '{parse('2035-04-01T20:00:00.000Z')}')")
    op.execute(
        f"INSERT INTO show (artist_id,venue_id, start_time) VALUES (3,3, '{parse('2035-04-08T20:00:00.000Z')}')")
    op.execute(
        f"INSERT INTO show (artist_id,venue_id, start_time) VALUES (3,3, '{parse('2035-04-15T20:00:00.000Z')}')")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'city', type_='foreignkey')
    op.drop_column('city', 'state_id')
    # ### end Alembic commands ###
