"""empty message

Revision ID: 8e83ab6dc685
Revises: f2d49d5ac091
Create Date: 2020-05-04 21:18:07.088118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e83ab6dc685'
down_revision = 'f2d49d5ac091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artist', 'state', ['state_id'], ['id'])
    op.drop_column('artist', 'city')
    op.drop_column('artist', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'state_id')
    # ### end Alembic commands ###
