"""empty message

Revision ID: 91f279b546ff
Revises: adbae09abc6e
Create Date: 2020-05-10 08:12:07.832552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f279b546ff'
down_revision = 'adbae09abc6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    state_table = op.create_table('state',
    sa.Column('id', sa.Integer),
    sa.Column('name', sa.String),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artist', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('city', sa.String(length=120), nullable=True))
    

    op.execute('UPDATE artist SET city= \'San Francisco\' WHERE id = 1')
    op.execute('UPDATE artist SET city = \'New York\' WHERE id = 2')
    op.execute('UPDATE artist SET city = \'San Francisco\' WHERE id = 3')
    op.execute('UPDATE venue SET city = \'San Francisco\' WHERE id = 1')
    op.execute('UPDATE venue SET city = \'New York\' WHERE id = 2')
    op.execute('UPDATE venue SET city = \'San Francisco\' WHERE id = 3')

    op.bulk_insert(
        state_table,
        [
            {'id': 1,'name':'AL'},
            {'id': 2,'name':'AK'},
            {'id': 3,'name':'AZ'},
            {'id': 4,'name':'AR'},
            {'id': 5,'name':'CA'},
            {'id': 6,'name':'CO'},
            {'id': 7,'name':'CT'},
            {'id': 8,'name':'DE'},
            {'id': 9,'name':'DC'},
            {'id': 10,'name':'FL'},
            {'id': 11,'name':'GA'},
            {'id': 12,'name':'HI'},
            {'id': 13,'name':'ID'},
            {'id': 14,'name':'IL'},
            {'id': 15,'name':'IN'},
            {'id': 16,'name':'IA'},
            {'id': 17,'name':'KS'},
            {'id': 18,'name':'KY'},
            {'id': 19,'name':'LA'},
            {'id': 20,'name':'ME'},
            {'id': 21,'name':'MT'},
            {'id': 22,'name':'NE'},
            {'id': 23,'name':'NV'},
            {'id': 24,'name':'NH'},
            {'id': 25,'name':'NJ'},
            {'id': 26,'name':'NM'},
            {'id': 27,'name':'NY'},
            {'id': 28,'name':'NC'},
            {'id': 29,'name':'ND'},
            {'id': 30,'name':'OH'},
            {'id': 31,'name':'OK'},
            {'id': 32,'name':'OR'},
            {'id': 33,'name':'MD'},
            {'id': 34,'name':'MA'},
            {'id': 35,'name':'MI'},
            {'id': 36,'name':'MN'},
            {'id': 37,'name':'MS'},
            {'id': 38,'name':'MO'},
            {'id': 39,'name':'PA'},
            {'id': 40,'name':'RI'},
            {'id': 41,'name':'SC'},
            {'id': 42,'name':'SD'},
            {'id': 43,'name':'TN'},
            {'id': 44,'name':'TX'},
            {'id': 45,'name':'UT'},
            {'id': 46,'name':'VT'},
            {'id': 47,'name':'VA'},
            {'id': 48,'name':'WA'},
            {'id': 49,'name':'WV'},
            {'id': 50,'name':'WI'},
            {'id': 51,'name':'WY'}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'city')
    op.drop_column('artist', 'city')
    op.drop_table('state')
    # ### end Alembic commands ###
