"""empty message

Revision ID: a3313865ecc6
Revises: 6acf2b69df7b
Create Date: 2020-05-08 21:39:12.516095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3313865ecc6'
down_revision = '6acf2b69df7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    show_table = op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


    op.bulk_insert(
    show_table,
    [{
        "id": 1,
        "artist_id": 1,
        "venue_id" : 1,
        "start_time": "2019-05-21T21:30:00.000Z"
    },{
        "id": 2,
        "artist_id": 2,
        "venue_id": 3,
        "start_time": "2019-06-15T23:00:00.000Z"
    },{
        "id": 3,
        "artist_id": 3,
        "venue_id": 3,
        "start_time": "2035-04-01T20:00:00.000Z"
    }, {
        "id": 4,
        "artist_id": 3,
        "venue_id": 3,
        "start_time": "2035-04-08T20:00:00.000Z"
    }, {
        "id": 5,
        "artist_id": 3,
        "venue_id": 3,
        "start_time": "2035-04-15T20:00:00.000Z"
    }])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
