"""empty message

Revision ID: b75c7e34f8ca
Revises: 91f279b546ff
Create Date: 2020-05-11 16:51:14.329907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75c7e34f8ca'
down_revision = '91f279b546ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    venue_state_table = op.create_table('venue_state',
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], )
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_state')
    # ### end Alembic commands ###
