"""empty message

Revision ID: f2d49d5ac091
Revises: 27e8a1a2c948
Create Date: 2020-05-04 21:07:12.730593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d49d5ac091'
down_revision = '27e8a1a2c948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
